### ISSUE TITLE
OpenAPIドキュメントの更新

### ISSUE THREAD

**Issue by itoshot** [Personal-Data-Linkage-Module/pxr-catalog-update-service#8]
```[tasklist]
### Tasks
- [ ] GET /actor/accreditor
- [ ] GET /actor
- [ ] POST /actor
- [ ] POST /actor/remove
- [ ] GET /join
- [ ] POST /join
- [ ] POST /join/remove
- [ ] GET /region
- [ ] POST /region
- [ ] POST /region/delete
- [ ] GET /region/status
- [ ] POST /region/status/start
- [ ] POST /region/status/end
- [ ] POST /platform-terms-of-use
- [ ] PUT /platform-terms-of-use
- [ ] POST /region-terms-of-use
- [ ] PUT /region-terms-of-use
- [ ] POST /store-event
- [ ] PUT /store-event
- [ ] POST /updateSet/request
- [ ] POST /updateSet/approval/:id
```
